/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_company_JNIAdapter */

#ifndef _Included_com_company_JNIAdapter
#define _Included_com_company_JNIAdapter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_company_JNIAdapter
 * Method:    getSizeTMax
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_company_JNIAdapter_getSizeTMax
  (JNIEnv *, jobject);

/*
 * Class:     com_company_JNIAdapter
 * Method:    callConstructor
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_company_JNIAdapter_callConstructor
  (JNIEnv *, jobject);

/*
 * Class:     com_company_JNIAdapter
 * Method:    callDestructor
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_company_JNIAdapter_callDestructor
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_company_JNIAdapter
 * Method:    getCurProcID
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_company_JNIAdapter_getCurProcID
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_company_JNIAdapter
 * Method:    getCurProcName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_company_JNIAdapter_getCurProcName
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_company_JNIAdapter
 * Method:    getCurProcThreadCnt
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_company_JNIAdapter_getCurProcThreadCnt
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_company_JNIAdapter
 * Method:    getProgramNameByActiveWindow
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_company_JNIAdapter_getProgramNameByActiveWindow
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_company_JNIAdapter
 * Method:    getCpuLoadByProcess
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_company_JNIAdapter_getCpuLoadByProcess
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_company_JNIAdapter
 * Method:    getRAMLoadByProcess
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_company_JNIAdapter_getRAMLoadByProcess
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_company_JNIAdapter
 * Method:    toNextProcess
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_company_JNIAdapter_toNextProcess
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_company_JNIAdapter
 * Method:    updateSnap
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_company_JNIAdapter_updateSnap
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
