/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_company_ClientMainClass */

#ifndef _Included_com_company_ClientMainClass
#define _Included_com_company_ClientMainClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_company_ClientMainClass
 * Method:    showString
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_company_ClientMainClass_showString
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
